# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: An Opinion on Software
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand

nav:
  - About Me:
      - Intro: index.md
      - Bio: about_me.md

  - A Day in the Life:
      - Monday: story/index.md
      - Bob's Task: story/bobs_task.md
      - Understanding the Task: story/sure_thing.md
      - Doing the Work: story/write_code.md
      - Pushing through the Process: story/policy_override.md
      - Deploying to Production: story/deploying_to_production.md
      - Fixing Production: story/fixing_production.md
      - Plan a Conversation: story/sticky_note.md
      - First of the Month: story/first_of_the_month.md
      - Results: story/results.md

  - Reference:
      - Good Software Engineers: reference/good_software_engineer.md
      - Agile Project Management:
        - Philosophy: reference/agile/overview.md
        - Components: reference/agile/components.md
        - Tools: reference/agile/implementation.md


markdown_extensions:
  - attr_list
