# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: An Opinion on Software
theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand

nav:
  - About Me:
      - Intro: index.md
      - Bio: about_me.md

  - A Day in the Life:
      - Monday: story/index.md
      - Bob's Task: story/bobs_task.md

  - Reference:
      - Good Software Engineers: reference/good_software_engineer.md
      - Agile Project Management:
        - Philosophy: reference/agile.md
        - Tools: reference/agile/implementation.md


markdown_extensions:
  - attr_list
